### ISSUE TITLE
Incorrect result on some inputs

### ISSUE THREAD

**Issue by Ekdohibs** [Kindelia/HVM#44] opened 2022-02-01 10:08 UTC
HVM produces incorrect results on some inputs, one of which being:
```
(Main arg) = ((λa (a (λb ((λc (λd (b (c d)))) a)))) (λe (e e)))
```
On this input, HVM produces the result `λx1 λx2 ((x1 x2) (x1 x2))` while the correct result is `λx1 λx2 ((x1 x1) (x2 x2))` (as verified by [https://crypto.stanford.edu/~blynn/lambda/](), with the corresponding input syntax by adding dots after the variable of each lambda: `((λa. (a (λb. ((λc. (λd. (b (c d)))) a)))) (λe. (e e)))`).

Besides, on other inputs such as:
```
((λa λb ((b a) λc λd (λe (d a) a)) λf (f f)) λz z)
```
HVM produces the result `λx1 (x1 λx2 (x2 _))` which is not even well-formed.

**Comment by VictorTaelin** [comment] 2022-02-01 10:22
This seems to be violating the "clones can't clone their own clones" limitation, explained [here](https://github.com/Kindelia/HVM/blob/master/HOW.md#superposed-duplication). HVM is just a (much) faster functional runtime based on the abstract algorithm, not a full λ-calculator. Attempting to make a clone clone its own clone is considered undefined behavior. I stress that this only happens in highly artificial examples (like these!).

**Comment by L-as** [comment] 2022-02-01 10:27
This limitation should probably be noted in the README. You probably also want to add more information on the limitation to make clear under what situations this is (im)possible. I assume this limitation is impossible to hit if the type system precludes applying a function to itself?

**Comment by Ekdohibs** [comment] 2022-02-01 10:30
While I agree it is ok if there are limitations, I find it a completely different matter to have limitations and to silently return an incorrect result!
Besides, it seems to me that this limitation could be easily violated in a "natural" program such as mapping over a list of lists: `map2 f l = map (map f) l`. The function `map` has to clone the function given to it (as it needs to call it several times), but `map f` contains a clone of `map` itself!

**Comment by VictorTaelin** [comment] 2022-02-01 10:36
@L-as yes, but that is still too restrictive. Applying a function to itself is fine (and even usual). For example, the Y-Combinator relies on applying `f` to itself: `Y = λf (λr(f (r r)) λr(f (r r)))`. That **is completely fine**. What is not allowed is for a *cloned function* to apply its own clone to itself. That is a much more rare situation. I'd bet there isn't a single occurrence of this in any of the Rust's top 1000 libraries, for example. There could be a note on the README, but is it really necessary. This, again, is way less restrictive than Rust's borrow checker, so I find it really confusing that people make a big deal of this.

**Comment by VictorTaelin** [comment] 2022-02-01 10:41
@Ekdohibs `map (map f) l` is completely fine! As is basically anything you'll come up with in practice. I think this is the main reason people get scared, they don't realize what the limitation really entails!

As to silently failing, that's just like every other undefined behavior, not unlike adding a number and a string, or reading arrays out of bounds. HVM is an untyped compile target, not meant to be a user-facing language. Obviously languages that compile to it will prevent these programs during type checking.

**Comment by Ekdohibs** [comment] 2022-02-01 10:43
Hmmm, I think I don't understand why `map (map f) l` is fine, at least if `map` is a lambda-bound function. (Imagine we are in Haskell and this function `map2` is defined for any functor).

**Comment by nothingnesses** [comment] 2022-02-01 10:44
Victor gave an example of what isn't allowed on the Telegram channel:

```
let f = λs. λz. (s (s z)) # a lambda that clones its argument
let g = f                 # a clone of that lambda
(g f)                     # the clone will clone the original
```

He said:
> this is a limitation of the runtime and should raise a type error, just like you can't have two concurrent &mut references in Rust

**Comment by VictorTaelin** [comment] 2022-02-01 10:49
I think people (myself included) misread the meaning of "a clone cloning its own clone". The `map` function creates copies of `f`. Then the outer `map` creates copies of `map f`. Under no circumstance any cloned function is attempting to clone itself. That would only happen if `map` called `f(f)`, **and** `f` cloned its input, **and** it called its input on itself. Like, this would be a problem:

```
(Map f (Cons x xs)) = (Map ((f f) x) xs)

(Main) = (Map λx(x x) ....)
```

But that's not the definition of `map`. Even if that was the definition of map... most mapped functions are linear (like `λx(+ x 1)`). And even when the mapped function isn't linear, it is almost never calling its argument on itself.

Do you see how far your example is from reaching the limit? It is difficult to even come up with well-typed examples that reach this limitation. Haskell's Church Nat is the only one I know, actually.

**Comment by Ekdohibs** [comment] 2022-02-01 10:58
Ah, I thought creating copies of `map f` would create copies of `map`, but I guess I'm mistaken about it. I've seen more than once your example above of writing the `double` function and calling it on itself, but it was mainly to test that compilers were correct. I'm still not sure about the precise conditions of "a clone cloning its own clone". Supposing `f` clones its argument, `f f` is not allowed. However, is `f 0 f` allowed if `f` clones its second argument? Is `f (\x. f x)` allowed? What about `f (f g)` and `f (g f)` depending on `g`? In any case, it seems non-obvious to me to come with a type system to forbid such clones, and I fear such a type system might be as difficult to understand as Rust's borrow checker...

**Comment by VictorTaelin** [comment] 2022-02-01 11:32
@Ekdohibs think about it like this:

1. Every duplicator on the source (`dup x y = term`) has a unique label.

2. A duplicator can't copy a term that has a duplicator with the same label as itself.

For example:

```
(λf(dup#0 x y = f; (x y)) λg(dup#1 a b = g; (a b)))
---------------------------------------------------
dup#0 x y = λg(dup#1 a b = g; (a b)); (x y)
---------------------------------------------------
(λg(dup#1 a b = g; (a b)) λg(dup#1 a b = g; (a b)))
---------------------------------------------------
dup#1 a b = λg(dup#1 a b = g; (a b)); (a b)
```

The last line is undefined behavior, because it has a dup with a `#1` label attempting to copy a function which has a dup with a `#1` label. Notice that the first level of self-copying is fine. It is when clones clone clones that you get a problem.

This can only happen when a function copies itself, and then the copy also copies itself. Emphasis on the "self". Functions copying other functions is fine. Repeated self-copying is the only way, because, otherwise, it would be impossible for two identical labels to collide, since every `dup` has a globally unique label.

In general, any program that isn't allowed is similar to `(λx(x x) λx(x x))` in shape. For example, the first program your posted is just a larger version of it:

```
(Main arg) = ((λa (a (λb ((λc (λd (b (c d)))) a)))) (λe (e e)))
(Main arg) = ((λa (a ........................ a..)) (λe (e e)))
```

And the second one expands to it after a few steps.

It is not hard to come up with a static checker for this requirement. For example, the old Formality-Core had one, but it was too restrictive, because it stratified programs in levels, so that a `dup` on level `X` could only copy terms on level `X+1`, avoiding this problem. A much better solution, I believe, would be to just track a function's lifecycle and make sure it isn't cloning itself, followed by its clones also cloning themselves.

**Comment by Ekdohibs** [comment] 2022-02-01 11:37
Ah, that makes it clearer, thank you! However, with this definition, I still think the Y-combinator will be undefined behavior.

**Comment by VictorTaelin** [comment] 2022-02-01 11:41
No, because the Y combinator just creates infinite copies of the function it receives, but it never actually copies itself, nor does the function it receives copy itself. But applying the Y-Combinator to itself is undefined behavior!

I understand your point that it might be annoying to demand such a checker for any language interested to compile to HVM, though. Perhaps we could provide a checker as part of HVM, somehow. I'll think about that.

**Comment by VictorTaelin** [comment] 2022-02-01 11:47
I'll close this issue and link to it on the needed improvements thread, in case anyone is interested in contributing with this in particular.

**Comment by Ekdohibs** [comment] 2022-02-01 11:52
In the Y-combinator case, it is neither the function it receives nor the Y-combinator which copies itself, but the `(\r. f (r r))` subterm. If we expand the body of the Y-combinator to `(\r. dup#0 s t =r ; f (s t)) (\r. dup#1 s t = r; f (s t))`, after a reduction it becomes `(\r. dup#1 s t = r; f (s t)) (\r. dup#1 s t = r; f (s t))`, and the `dup#1` needs to copy a `dup#1`.

**Comment by Ekdohibs** [comment] 2022-02-01 11:55
@VictorTaelin (it seems like I can't reopen the issue, since you were the one to close it, however).

**Comment by VictorTaelin** [comment] 2022-02-01 12:30
Ah, that is a fair point, a sub-term of the Y-combinator does clone itself, and then that clone clones itself again. That should be undefined behavior according to my explanation, so you're right. What happens, though, is that the duplication process is never finished, because `(r r)` gets pushed infinitely down the recursion, so it actually works fine. The Y-Combinator is a pretty peculiar term. It even has a normal form:

```
dup#1 s t = r; 
dup#1 S T = R;
(λr(f (s t)) λR(f (S T)))
-------------------------
dup#1 s t = λR(f (S T)); 
dup#1 S T = R;
(f (s t))
-------------------------
dup#1 s t = (f (S T)); 
dup#1 S T = #1{R0 R1};
(f (λR0(s) λR1(t)))
-------------------------
dup#1 s t = (f (S T)); 
dup#1 S T = #1{λR1(t) R1};
(f s)
-------------------------
dup#1 s t = (f (λR1(t) R1)); 
(f s)
-------------------------
dup#1 s t = (f t); 
(f s)
```

Note that this "normal form" represents `(f (f (f (f (f ....)))))`. Anyway, you're right, a *complete* criteria for acceptance would be a little complex. But the description I provided gives us a fairly reasonable language already, I think. A "clone checker" doesn't need to cover all programs that don't produce undefined behavior, it just must result in a practical language. It is a similar situation with Rust: there are many correct programs that the borrow checker simply can't identify as such. A clone checker would perhaps be a whitelist of patterns which we know to be safe.

**Comment by Ekdohibs** [comment] 2022-02-01 12:46
I agree, the Y-combinator works correctly, even if it is undefined behaviour. In fact, what I think happens is that we get a duplication confusion (which often produces errors), but here instead, since the Y-combinator has a rather peculiar form, gives us the correct result, albeit with a term containing loops(!).
I also found a slightly unsual example, but one that you could see in a real program that should cause a clone error: imagine you have a list of functions, and you want to map each of these functions over a list (that could happen with a list monad for instance). You would have a term of the form `map (\f. map f values) functions`, and if I'm not mistaken, in this case, map will duplicate its argument, which contains itself a clone of map that will be duplicated (the difference with before being that since the function is statically unknown, the duplication will wait for each call of the function, thus keeping an unreduced `dup`).

**Comment by L-as** [comment] 2022-02-01 13:09
@VictorTaelin When would you ever apply a function to itself in a standard functional language like Haskell or OCaml?

**Comment by VictorTaelin** [comment] 2022-02-01 16:35
tI don' think that case is problematic, but I can try later.

@L-as applying a function to itself is not that rare. I can only think of Church-Nats, and to create the Y-Combinator). Having to do that once again with the result is quite rare.

**Comment by Ekdohibs** [comment] 2022-02-03 09:10
With the following code I get incorrect results (as expected):
```
(Map Nil f) = Nil
(Map (Cons x xs) f) = (Cons (f x) (Map xs f))

(Main arg) =
  let l1 = (Cons (λx(x)) (Cons (λx(+ x 2)) Nil))
  let l2 = (Cons 0 (Cons 1 Nil))
  (Map l1 (λf(Map l2 f)))
```
The result given by HVM is `(Cons (Cons 0 (Cons 3 (Nil))) (Cons (Cons 0 (Cons 3 (Nil))) (Nil)))` while `(Cons (Cons 0 (Cons 1 (Nil))) (Cons (Cons 2 (Cons 3 (Nil))) (Nil)))` is expected and is what we get if we replace an instance of Map by an identical copy.

However, I (personally) find this code to be very reasonable: no self-application, only the classic "Map" function is used, and the most unusual part is arguably the list of functions (which is not even that unusual).

**Comment by VictorTaelin** [comment] 2022-02-06 13:04
@Ekdohibs your program doesn't hit the limit because of a limitation of the abstract algorithm, but of a temporary HVM gist: it currently does **not** assign different labels to different uses of the same global function. That will be patched soon, and your proogram will work. As a temporary fix, you could just have two map functions:

```
(Map0 Nil         f) = Nil
(Map0 (Cons x xs) f) = (Cons (f x) (Map0 xs f))

(Map1 Nil         f) = Nil
(Map1 (Cons x xs) f) = (Cons (f x) (Map1 xs f))

(Main arg) =
  let l1 = (Cons (λx(x)) (Cons (λx(+ x 2)) Nil))
  let l2 = (Cons 0 (Cons 1 Nil))
  (Map0 l1 (λf(Map1 l2 f)))
```

(But again, that's not necessary, since it will be patched soon.)

**Comment by Ekdohibs** [comment] 2022-02-06 13:15
While i completely agree that this fixes the issue (which is what I meant by "replacing one instance by an indentical function" above), this would not work if `Map` was a function argument instead of a global function (think functors and monads for instance: in the case of monads, This very function, of type `Monad m => m (a -> b) -> m a -> m b` exists in Haskell and is the well-known and very used function `<*>`!).

**Comment by VictorTaelin** [comment] 2022-02-06 13:16
@Ekdohibs I don't think that is true. Even if `Map` was built locally with `Fix`, the `Fix` function itself would give it brand new labels every time it is generated; right? Or what else you have in mind?

**Comment by Ekdohibs** [comment] 2022-02-06 13:55
What I had in mind was a function whose body was the expression above that took `Map` as an argument, sorry for the confusion.

**Comment by L-as** [comment] 2022-02-06 15:18
In Haskell the code might be
```haskell
x :: Applicative m => m [[Int]]
x =
  let l1 = ((\x -> x) : (\x -> x + 2) : []) in
  let l2 = (0 : 1 : []) in
  pure $ pure (\f -> pure f <*> l2) <*> l1
```

While not entirely natural, it goes to show that completely legal Haskell exists, whiles not being valid in HVM.

Unfortunately I don't think HVM will be usable for Haskell unless *all* legal Haskell is covered, or at the very least a large subset that tells you when you step outside it.

**Comment by L-as** [comment] 2022-02-06 15:35
I just realised that my code accidentally uses the `Applicative` for lists.

The following is perhaps a better example:
```haskell
x :: (forall a b. (a -> b) -> [a] -> [b]) -> [[Int]]
x mymap =
  let l1 = ((\x -> x) : (\x -> x + 2) : []) in
  let l2 = (0 : 1 : []) in
  mymap (\f -> mymap f l2) l1
```

**Comment by Ekdohibs** [comment] 2022-02-06 18:44
The code I had in mind was something like:
```haskell
f :: Monad m -> m (a -> b) -> m a -> m b
f x1 x2 = join $ fmap (\f -> fmap f x2) x1

x = f ((\x -> x) : (\x -> x+ 2) : []) (0 : 1 : [])
```

**Comment by phischu** [comment] 2022-08-09 08:07
I just want to say that apparently the original issue has been fixed. The following program:

    (Map Nil f) = Nil
    (Map (Cons x xs) f) = (Cons (f x) (Map xs f))

    (Main arg) =
      let l1 = (Cons (λx(x)) (Cons (λx(+ x 2)) Nil))
      let l2 = (Cons 0 (Cons 1 Nil))
      (Map l1 (λf(Map l2 f)))

Evaluates to

    (Cons (Cons 0 (Cons 1 (Nil))) (Cons (Cons 2 (Cons 3 (Nil))) (Nil)))

Moreover, the following program (which I conjecture has been working correctly all the time):

    (Map Nil f) = Nil
    (Map (Cons x xs) f) = (Cons (f x) (Map xs f))

    (Mapping mymap) =
      let l1 = (Cons (λx(x)) (Cons (λx(+ x 2)) Nil))
      let l2 = (Cons 0 (Cons 1 Nil))
      (mymap l1 (λf(mymap l2 f)))

    (Main arg) =
      (Mapping (λlλf(Map l f)))

Evaluates to:

    (Cons (Cons 0 (Cons 1 (Nil))) (Cons (Cons 2 (Cons 3 (Nil))) (Nil)))

As a meta remark, I am completely with Victor here as I do not understand why this whole thing is so important to some people. It really is a very very obscure corner case that untyped lambda calculus unfortunately has.

**Comment by L-as** [comment] 2022-08-09 09:28
The issue is that HVM is fundamentally unusable for most functional programming languages unless this is fixed at its root.
Supporting the full LC is not a necessity, but when you go from e.g. GHC Core to HVM, there must be a way of detecting whether this GHC Core term can be translated to HVM. It is possible to make a naïve "type checker" for this, but it's very hard to make one that supports a language expressive enough to support common Haskell idioms AFAIK.
If you can _not_ guarantee that, then it's not useful in real-world applications.
Why would you build a program that _maybe_ works, when hitting the limit is possible with trivial and standard Haskell code?

**Comment by eliasvasylenko** [comment] 2022-08-24 09:39
For HVM to be a useful target for existing functional languages like Haskell it is not necessary to remove this limitation. Rather, what is needed is to detect when this limit is (possibly) hit, and then mechanically transform the program into an equivalent one which does _not_ hit this limit. Is such a transformation possible?

**Comment by VictorTaelin** [comment] 2022-11-23 04:24
I'm closing this issue as this should be the user-facing language responsibility to compile compatible terms. [Kind-Lang](https://github.com/kindelia/kind) will do so soon, and we'll be providing materials on how to accomplish this to compile any other language to HVM.

**Closed by VictorTaelin** 2022-11-23 04:24 UTC
Labels: discussion

**Comment by Kesanov** [comment] 2022-12-12 12:53
I think it would be useful to have a "debug" mode, that would throw a runtime error and halt the execution when this undefined behaviour is encountered.
This might make HVM great compilation target even for untyped languages. It would also simplify debugging compiler writers or curious people that just want to play with HVM.

**Comment by LPTK** [comment] 2022-12-14 07:27
If HVM is not a Lambda Calculus runtime, then isn't comparing it with GHC-compiled Haskell, as done on the main page, comparing apples with oranges?

I had  the feeling that HVM was advertised as a possible alternative backend for functional programming languages, assuming that some (for now unspecified) type system is added to check that the terms being compiled don't exercise the part where HVM semantics differ (clone that clones itself etc.). Are you now saying that this endeavor is misguided?

> it wouldn't make sense to halt execution even if it was possible to detect such divergent cases (and it isn't)

It seems that as long as the divergent case is rigorously specified in terms such as "a clone shouldn't clone itself", it should be possible to check at runtime, even though possibly at great runtime cost. I am curious to hear what it is that makes you think this is in fact impossible.

**Comment by jdehaan** [comment] 2022-12-14 07:44
To my understanding computing is computing no matter if the system is using a turing machine approach, interaction nets or lambda calculus, let the most efficient approach (or implementation of it) win.

**Comment by VictorTaelin** [comment] 2022-12-14 14:05
That isn't what I meant. What I said is that divergent terms shouldn't be UB or abort because HVM will give you the correct answer w.r.t Interaction Net semantics, and someone could very well use HVM as an Interaction Net runtime. That isn't mutually exclusive with HVM being a suitable functional runtime. It is a good idea to compile a functional language to HVM, you just need to keep in mind that you need a checker for compatibility, possibly in the shape of an elementary affine type inferencer or something similar.

**Comment by LPTK** [comment] 2022-12-14 15:15
Right, so I think you got hung up on @Kesanov's use of "undefined behavior". I think they meant that terms with divergent semantics could be defined as UB _from the point of view_ of a lambda-calculus-based functional language implementation that would compile to HVM. I.e., the compiler would guarantees lambda-calculus semantics within some boundaries, and outside of these boundaries all bets would be off, which is what would allow it to optimize the code (by compiling to HVM).

Now, @Kesanov was not suggesting that HVM crash on divergent programs, but just that it would be useful (for developers of lambda-calculus compilers) to have a _debug mode_ to detect these divergent cases, just like address sanitizers and other instrumentations can detect when a program goes outside of its semantically-specified subset. Do you still think this would be impossible to implement?

**Comment by VictorTaelin** [comment] 2022-12-15 05:07
Ah, I see. Sadly, I'm not sure how that could be implemented. After the initial compilation from λ-calculus to interaction nets, the graph will go through intermediate states that don't even correspond to λ-terms. It is not obvious to me how we could identify exactly when a divergence occurs. But I'm not sure if that's not possible either; perhaps there is some easy way to do so. I'll reply here again if I have any additional insight.

**Comment by Boscop** [comment] 2023-05-01 12:50
@VictorTaelin What do you think about this?:
> An impure solution to the problem of matching fans: https://arxiv.org/abs/1710.07516

This only requires a (concurrent) hashmap.
It's implemented here https://github.com/codedot/lambda and online demo here: https://codedot.github.io/lambda/
E.g. if you enter `(g: g g) (s: z: s (s z))`, you get the right result `v1, v2: v1 (v1 (v1 (v1 v2)))`.
(And if you enter @Ekdohibs's original term as `((a: (a (b: ((c: (d: (b (c d)))) a)))) (e: (e e)))`, you get the expected result `v1, v2: v1 v1 (v2 v2)`.)

In the [benchmarks table](https://github.com/codedot/lambda#benchmarks), it shows that it reaches the result in fewer interactions than other approaches.
Although it fails to reduce the term [`(f: f (f (x: x))) (i: (f: f (x: x) (f (x: x))) (x: (h, u: h (h u)) (y: x (i y))))`](https://github.com/codedot/lambda/blob/master/samples/counter.mlc) for some reason.

**Comment by VictorTaelin** [comment] 2023-05-10 22:48
If my memory doesn't fail me, this paper doesn't prove correctness, and later on Anton found some counter-examples to it, so the solution is wrong. But I could be mistaken about that. The solution is interesting if it works, but a proof would be needed to rely on it.
