### ISSUE TITLE
Performance regression on HVM v1.0

### ISSUE THREAD

**Issue by developedby** [Kindelia/HVM#179] opened 2022-11-24 17:34 UTC
Doing some basic tasks with the new version of hvm, I'm seeing some considerable performance regression compared to the old version (v0.1.89)

With this simple fibonacci program:
```
(Fib 0 x0 x1) = x0
(Fib idx x0 x1) = (Fib (- idx 1) x1 (+ x0 x1))
(Main) = (Fib <n> 0 1)
```
The number of rewrites scales linearly with `n`, and so does the number of accumulated dup nodes.
On the old HVM, the time used for this program scales linearly. On the new HVM it scales quadractically, even though the number of rewrites and space used is the same on both..

If I make the `x1` variable strict by adding an extra rule like so, we don't accumulate dups anymore
```
(Fib 0 x0 x1) = x0
(Fib idx x0 x1) = (Fib (- idx 1) x1 (+ x0 x1))
(Fib idx x0 0) = 0
(Main) = (Fib 1000000 0 1)
```
The performance on the old HVM is the same as before, but on the new version it becomes linear.

Besides this slowdown from dups, I'm also seeing a large regression on the single-core interpreted execution of this same program. On the old HVM I get ~55MR/s, while on the new version I get just ~30MR/s.

I know @felipegchi also noticed a significant performance regression for running the Kind typechecker, seing a very large slowdown.

**Comment by VictorTaelin** [comment] 2022-11-26 05:45
Can you help me identifying the source of this regression? 

Regarding the constant-time slowdown, I expect the use of atomic u64s instead of u64 to cause such regression. The locking of dups could also add up. Moreover, the use of a Visit Stack and a Redex Bag could impact it. These things are necessary for synchronization. If that's the case, we could disable atomics entirely on single core, and aim to reduce the usage of atomics and locks to only when it is necessary on multiple cores. That would probably improve the peak parallel speed too.

Regarding a program taking quadratic time to perform the same number of rewrites, that makes absolutely no sense to me. Perhaps it is a bug where the `reduce` function returns prematurely for some reason? This would make the program reduce partially, which would cause `normalize` to execute repeatedly, thus re-traversing the term unnecessarily. That's the only thing I can think of. Would be good to debug and have a confirmation.

**Comment by VictorTaelin** [comment] 2022-11-28 07:28
The commit above fixes that issue, but it has some problems that must be fixed before we merge. Locks use too much space. I'll work on this later on. Can you test how that branch performs?

**Comment by developedby** [comment] 2022-11-28 10:56
On the example I gave in this issue, I'm seeing a 5-10% slowdown on the `lock_fix' branch for both multithreaded and single-thread, but the problem with the dups does seem to be solved.

**Comment by VictorTaelin** [comment] 2022-11-28 16:11
Thanks, that problem is likely caused by the `FIXME` line on the commit. Can you try without it?

**Comment by developedby** [comment] 2022-11-29 17:05
Tried some different test, but that line in specific doesn't seem to affect perfomance in a relevant way. If anything, removing it makes everything 1~2% slower, but that's probably just random noise

**Comment by VictorTaelin** [comment] 2022-12-02 07:53
Fixed the space wasted by the new locks and merged on `master`. There is still a FIXME issue that we must look in a future, as it seems to cause the `Fib` program to fail sporadically, but I believe this is an entirely unrelated issue that has been uncovered by the fact threads are now acting faster and eager to enter steal mode after they visit a locked dup.

```
// List type
(Head (Cons x xs)) = (Some x)
(Head Nil) = None

// Something like Rust's Option.unwrap_or
(UnwrapOr (Some x) y) = x
(UnwrapOr None y) = y

(SumFirstTwo Nil) = 0 
(SumFirstTwo (Cons x xs)) = (+ x (UnwrapOr (Head xs) 0))

// Iterate a function n times on an input
(Iter f x 0) = x
(Iter f x n) = (f (Iter f x (- n 1)))

(Fib n) = (Head (Iter λxs (Cons (SumFirstTwo xs) xs) (Cons 0 (Cons 1 Nil)) n))

(Main n) = (Fib 15000)
```

**Comment by VictorTaelin** [comment] 2022-12-02 23:29
I had to revert this because it cause some other programs not to compute. I'll revisit this issue next week.

**Comment by VictorTaelin** [comment] 2022-12-05 03:51
Should be fixed for now. See the comments on #181

**Closed by VictorTaelin** 2022-12-05 03:51 UTC
